# Generated by Django 5.0.14 on 2026-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_tramite_archivo_pdf_firmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tipo_documento',
            field=models.CharField(choices=[('OFICIO', 'Oficio Genérico'), ('CERTIFICADO', 'Oficio (Certificación de Datos)')], max_length=20),
        ),
    ]
