# Generated by Django 5.0.14 on 2026-01-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_alter_tramite_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tipo_documento',
            field=models.CharField(choices=[('OFICIO', 'Oficio'), ('CERTIFICADO', 'Certificado')], max_length=20),
        ),
    ]
