# Generated by Django 5.0.14 on 2026-02-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0005_alter_tramite_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='pregunta_adicional',
            field=models.TextField(blank=True, help_text='Pregunta adicional del solicitante al crear el trámite'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='respuesta_pregunta',
            field=models.TextField(blank=True, help_text='Respuesta a la pregunta adicional, escrita por el revisor al aprobar'),
        ),
    ]
