# Generated by Django 5.0.14 on 2026-02-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0006_tramite_pregunta_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='datos_qa',
            field=models.JSONField(blank=True, default=dict, help_text='Estructura QA para múltiples empresas: {id_empresa: {nombre, pregunta, respuesta}}'),
        ),
    ]
