# Generated by Django 5.0.14 on 2026-02-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0007_tramite_datos_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='cargo_solicitante',
            field=models.CharField(blank=True, help_text='Cargo del solicitante externo', max_length=200),
        ),
        migrations.AddField(
            model_name='tramite',
            name='carpetilla',
            field=models.CharField(blank=True, help_text='Número de Carpetilla (ej: 202300074865)', max_length=100),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_oficio_entrante',
            field=models.DateField(blank=True, help_text='Fecha del oficio entrante', null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_recepcion',
            field=models.DateField(blank=True, help_text='Fecha de recepción en el despacho', null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='institucion_solicitante',
            field=models.CharField(blank=True, help_text='Institución solicitante (ej: Ministerio Público)', max_length=200),
        ),
        migrations.AddField(
            model_name='tramite',
            name='oficio_entrante',
            field=models.CharField(blank=True, help_text='Número de Oficio entrante (ej: Oficio No. 478-2024)', max_length=100),
        ),
        migrations.AddField(
            model_name='tramite',
            name='solicitante_externo',
            field=models.CharField(blank=True, help_text='Nombre del funcionario solicitante externo (ej: Lic. Caren Cabeza)', max_length=200),
        ),
    ]
